server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.46.137
  rabbitmq:
    host: 192.168.46.137
    virtual-host: /guoquan
    username: guoquan
    password: 123456

auth:
  jwt:
    publicKeyPath: D:\\IDEA_PROJECT\\secret\\rsa.pub
    cookieName: GMALL_TOKEN
    userKeyName: userKey
    expireTime: 2592000